Table dim_cliente {
  id_cliente BIGINT
  nome_cliente TEXT
  whatsapp TEXT
  empresa TEXT
}

Table dim_pagamentos_programados {
  id_venda_consigcar BIGINT
  valor FLOAT
  id_data TEXT
}

Table dim_parcelamento {
  id_parcelamento INTEGER [pk]
  num_parcelas SMALLINT
  valor_parcela DECIMAL(10, 2)
  valor_total DECIMAL(10, 2)
  data_primeira_parcela INTEGER
  data_ultima_parcela INTEGER
}

Table dim_tempo {
  id_data BIGINT
  data DATETIME
  dia INTEGER
  mes INTEGER
  ano INTEGER
  nome_mes TEXT
  dia_da_semana TEXT
  trimestre INTEGER
}

Table dim_vendedor {
  id_vendedor BIGINT
  nome_vendedor TEXT
}

Table fato_consigcar_estimativa {
  id_data BIGINT
  valor_receita_estimativa FLOAT
}

Table fato_despesas {
  id_despesa BIGINT
  origem TEXT
  categoria TEXT
  nome_despesa TEXT
  valor FLOAT
  id_data BIGINT
}

Table fato_faturamento_pagseguro {
  id_faturamento BIGINT
  id_data BIGINT
  valor_faturado FLOAT
}

Table fato_metas_alucar {
  id_data BIGINT
  meta_vendas_1_cum BIGINT
  meta_vendas_2_cum BIGINT
  meta_vendas_1_mes FLOAT
  meta_vendas_2_mes FLOAT
}

Table fato_metas_consigcar {
  id_data BIGINT
  meta_vendas_1_cum BIGINT
  meta_vendas_2_cum BIGINT
  meta_vendas_1_mes FLOAT
  meta_vendas_2_mes FLOAT
}

Table fato_vendas_alucar {
  id_venda_alucar BIGINT
  id_cliente BIGINT
  id_data BIGINT
  valor_venda FLOAT
}

Table fato_vendas_clientes_alucar_estimativa {
  nome TEXT
  id_data BIGINT
  valor_receita_estimativa FLOAT
}

Table fato_vendas_consigcar {
  id_venda_consigcar BIGINT
  id_cliente BIGINT
  tipo_produto TEXT
  id_vendedor BIGINT
  num_parcelas BIGINT
  valor_parcela FLOAT
  valor_total FLOAT
  data_primeira_parcela BIGINT
  data_ultima_parcela BIGINT
}

Table fato_vendas_diaria_vendedor {
  id_vendedor BIGINT
  id_data BIGINT
  total_vendas BIGINT
  valor_total FLOAT
}

